FROM node:22.19.0-alpine AS build

WORKDIR /app/frontend
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci
COPY frontend/angular.json frontend/tsconfig*.json frontend/karma.conf.js ./
COPY frontend/src ./src
RUN npm run build:prod

FROM nginx:1.27-alpine
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/frontend/dist/repair-crm-client /usr/share/nginx/html
