"""Pydantic schemas, split by domain (aligned with ``app.routers``)."""

from .auth import (
    ChallengeResponse,
    LoginRequest,
    LogoutRequest,
    PasswordResetConfirmRequest,
    PasswordResetRequest,
    RefreshTokenRequest,
    RegisterRequest,
    TokenResponse,
)
from .common import ApiError, AuthPolicy
from .customer import ContactSchema, PortalCustomerSchema
from .mobile import (
    CustomerSessionSchema,
    MobileDeviceRegisterRequest,
    MobileDeviceSchema,
    PushTestRequest,
)
from .orders import (
    ApprovalDecisionRequest,
    OrderCreateRequest,
    PortalAdditionalServiceSchema,
    PortalApprovalSchema,
    PortalDeviceDetailSchema,
    PortalOrderSchema,
    PortalOrdersPage,
    PortalOrganizationSchema,
    PortalPaymentSchema,
    PortalRepairStageSchema,
    PortalShopSchema,
    PortalWarrantySchema,
    PublicTrackRequest,
)
from .profile import (
    ContactCreateRequest,
    ProfileUpdateRequest,
    VerificationConfirmRequest,
    VerificationRequest,
)
from .settings import (
    AuthSettings,
    BrandSettings,
    PortalBannerSchema,
    PortalMarketingSchema,
    PortalPromotionItemSchema,
    PortalPublicLocationSchema,
    PortalSettingsResponse,
)
from .sync import (
    ClientActionSchema,
    MarkActionSyncedRequest,
    SyncActionsResponse,
    SyncMarketingRequest,
    SyncMarketingResponse,
    SyncOrderItem,
    SyncOrderResponseItem,
    SyncOrdersRequest,
    SyncOrdersResponse,
)

__all__ = [
    "ApiError",
    "AuthPolicy",
    "AuthSettings",
    "ApprovalDecisionRequest",
    "BrandSettings",
    "ChallengeResponse",
    "ClientActionSchema",
    "ContactCreateRequest",
    "ContactSchema",
    "CustomerSessionSchema",
    "LoginRequest",
    "LogoutRequest",
    "MarkActionSyncedRequest",
    "MobileDeviceRegisterRequest",
    "MobileDeviceSchema",
    "OrderCreateRequest",
    "PasswordResetConfirmRequest",
    "PasswordResetRequest",
    "PortalAdditionalServiceSchema",
    "PortalApprovalSchema",
    "PortalBannerSchema",
    "PortalCustomerSchema",
    "PortalDeviceDetailSchema",
    "PortalMarketingSchema",
    "PortalOrderSchema",
    "PortalOrdersPage",
    "PortalOrganizationSchema",
    "PortalPaymentSchema",
    "PortalPromotionItemSchema",
    "PortalPublicLocationSchema",
    "PortalRepairStageSchema",
    "PortalSettingsResponse",
    "PortalShopSchema",
    "PortalWarrantySchema",
    "ProfileUpdateRequest",
    "PublicTrackRequest",
    "PushTestRequest",
    "RefreshTokenRequest",
    "RegisterRequest",
    "SyncActionsResponse",
    "SyncMarketingRequest",
    "SyncMarketingResponse",
    "SyncOrderItem",
    "SyncOrderResponseItem",
    "SyncOrdersRequest",
    "SyncOrdersResponse",
    "TokenResponse",
    "VerificationConfirmRequest",
    "VerificationRequest",
]
